# Deployment do MongoDB

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten-db
spec:
  selector:
    matchLabels:
      app: rotten-db
  template:
    metadata:
      labels:
        app: rotten-db
    spec:
      containers:
      - name: rotten-db
        image: mongo:5
        volumeMounts:
            - mountPath: /data/db
              name: mongo-data
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongouser
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongopwd
      volumes:
        - name: mongo-data
          hostPath:
            path: /volumes/mongodb

---

# Service do MongoDB
apiVersion: v1
kind: Service
metadata:
  name: rotten-db
spec:
  selector:
    app: rotten-db
  ports:
  - port: 27017
  type: ClusterIP

---

# Deployment da aplicação Web Rotten Potatoes

apiVersion: apps/v1
kind: Deployment
metadata:
  name: roten-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roten-app
  template:
    metadata:
      labels:
        app: roten-app
    spec:
      containers:
      - name: roten-app
        image: maiconnf1980/rotten-potatoes
        env:
        - name: MONGODB_DB
          value: admin
        - name: MONGODB_HOST
          value: rotten-db
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: mongouser
        - name: MONGODB_PASSWORD
          value: mongopwd

---
# Service da Aplicação
apiVersion: v1
kind: Service
metadata:
  name: roten-app
spec:
  selector:
    app: roten-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30084
  type: NodePort